# Generated by Django 3.2.9 on 2022-02-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0002_category_content_programme_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Content', 'verbose_name_plural': 'Content'},
        ),
        migrations.AlterModelOptions(
            name='programme',
            options={'verbose_name': 'Programme', 'verbose_name_plural': 'Programme'},
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Content Image'),
        ),
    ]
