# Generated by Django 3.2.9 on 2022-02-27 13:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0003_auto_20220226_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Content Image'),
        ),
    ]
