# Generated by Django 3.2.9 on 2022-02-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0007_alter_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='contents/%Y/%m/%d/', verbose_name='Content Image'),
        ),
    ]
