# Generated by Django 3.2.9 on 2022-03-02 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0008_alter_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='duration',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WEB.category'),
        ),
    ]
