# Generated by Django 3.2.9 on 2022-05-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0009_auto_20220302_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Short Course', 'Short Course')], max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name=''),
        ),
    ]
